name: CI Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop
      - master
    paths:
      - 'src/**'
      - 'public/**'
      - '.github/workflows/main.yml'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    # Set up js package
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Set package version and name
      uses: brown-ccv/gh-actions/get-package-info@master
      id: package_info

    # install, test, build package
    - name: npm install
      run: npm install
    - name: npm build
      run: npm run build


    # Build electron app package installers
    - name: package electron - windows
      if: startsWith(matrix.os, 'windows')
      run: npm run package:windows
    - name: package electron - linux
      if: startsWith(matrix.os, 'ubuntu')
      run: npm run package:linux


    # Upload installers to github action
    - name: upload win-installer
      uses: actions/upload-artifact@master
      if: startsWith(matrix.os, 'windows')
      with:
        name: win-installer
        path: dist/installers/${{ steps.package_info.outputs.package_name }}-${{ steps.package_info.outputs.package_version }}-setup.exe
    - name: upload linux-installer
      uses: actions/upload-artifact@master
      if: startsWith(matrix.os, 'ubuntu')
      with:
        name: linux-installer
        path: dist/installers/${{ steps.package_info.outputs.package_name }}_${{ steps.package_info.outputs.package_version }}_x64.deb
